# Generated by Django 6.0.2 on 2026-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="basic_salary",
            field=models.FloatField(default=0),
        ),
    ]
