# Generated by Django 6.0.2 on 2026-04-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_remove_employee_basic_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="basic_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
