# Generated by Django 6.0.2 on 2026-04-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employee_basic_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="basic_salary",
        ),
    ]
